// Code generated by mockery. DO NOT EDIT.

package adapter

import (
	model "github.com/mouse-blink/gooze/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockUI is an autogenerated mock type for the UI type
type MockUI struct {
	mock.Mock
}

type MockUI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUI) EXPECT() *MockUI_Expecter {
	return &MockUI_Expecter{mock: &_m.Mock}
}

// DisplayMutationEstimations provides a mock function with given fields: estimations
func (_m *MockUI) DisplayMutationEstimations(estimations map[model.Path]int) error {
	ret := _m.Called(estimations)

	if len(ret) == 0 {
		panic("no return value specified for DisplayMutationEstimations")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(map[model.Path]int) error); ok {
		r0 = rf(estimations)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUI_DisplayMutationEstimations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisplayMutationEstimations'
type MockUI_DisplayMutationEstimations_Call struct {
	*mock.Call
}

// DisplayMutationEstimations is a helper method to define mock.On call
//   - estimations map[model.Path]int
func (_e *MockUI_Expecter) DisplayMutationEstimations(estimations interface{}) *MockUI_DisplayMutationEstimations_Call {
	return &MockUI_DisplayMutationEstimations_Call{Call: _e.mock.On("DisplayMutationEstimations", estimations)}
}

func (_c *MockUI_DisplayMutationEstimations_Call) Run(run func(estimations map[model.Path]int)) *MockUI_DisplayMutationEstimations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(map[model.Path]int))
	})
	return _c
}

func (_c *MockUI_DisplayMutationEstimations_Call) Return(_a0 error) *MockUI_DisplayMutationEstimations_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUI_DisplayMutationEstimations_Call) RunAndReturn(run func(map[model.Path]int) error) *MockUI_DisplayMutationEstimations_Call {
	_c.Call.Return(run)
	return _c
}

// ShowNotImplemented provides a mock function with given fields: count
func (_m *MockUI) ShowNotImplemented(count int) error {
	ret := _m.Called(count)

	if len(ret) == 0 {
		panic("no return value specified for ShowNotImplemented")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(count)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUI_ShowNotImplemented_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShowNotImplemented'
type MockUI_ShowNotImplemented_Call struct {
	*mock.Call
}

// ShowNotImplemented is a helper method to define mock.On call
//   - count int
func (_e *MockUI_Expecter) ShowNotImplemented(count interface{}) *MockUI_ShowNotImplemented_Call {
	return &MockUI_ShowNotImplemented_Call{Call: _e.mock.On("ShowNotImplemented", count)}
}

func (_c *MockUI_ShowNotImplemented_Call) Run(run func(count int)) *MockUI_ShowNotImplemented_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockUI_ShowNotImplemented_Call) Return(_a0 error) *MockUI_ShowNotImplemented_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUI_ShowNotImplemented_Call) RunAndReturn(run func(int) error) *MockUI_ShowNotImplemented_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUI creates a new instance of MockUI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUI {
	mock := &MockUI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
