// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	model "github.com/mouse-blink/gooze/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockReportStore is an autogenerated mock type for the ReportStore type
type MockReportStore struct {
	mock.Mock
}

type MockReportStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReportStore) EXPECT() *MockReportStore_Expecter {
	return &MockReportStore_Expecter{mock: &_m.Mock}
}

// CheckUpdates provides a mock function with given fields: path, sources
func (_m *MockReportStore) CheckUpdates(path model.Path, sources []model.Source) ([]model.Source, error) {
	ret := _m.Called(path, sources)

	if len(ret) == 0 {
		panic("no return value specified for CheckUpdates")
	}

	var r0 []model.Source
	var r1 error
	if rf, ok := ret.Get(0).(func(model.Path, []model.Source) ([]model.Source, error)); ok {
		return rf(path, sources)
	}
	if rf, ok := ret.Get(0).(func(model.Path, []model.Source) []model.Source); ok {
		r0 = rf(path, sources)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Source)
		}
	}

	if rf, ok := ret.Get(1).(func(model.Path, []model.Source) error); ok {
		r1 = rf(path, sources)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReportStore_CheckUpdates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckUpdates'
type MockReportStore_CheckUpdates_Call struct {
	*mock.Call
}

// CheckUpdates is a helper method to define mock.On call
//   - path model.Path
//   - sources []model.Source
func (_e *MockReportStore_Expecter) CheckUpdates(path interface{}, sources interface{}) *MockReportStore_CheckUpdates_Call {
	return &MockReportStore_CheckUpdates_Call{Call: _e.mock.On("CheckUpdates", path, sources)}
}

func (_c *MockReportStore_CheckUpdates_Call) Run(run func(path model.Path, sources []model.Source)) *MockReportStore_CheckUpdates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.Path), args[1].([]model.Source))
	})
	return _c
}

func (_c *MockReportStore_CheckUpdates_Call) Return(_a0 []model.Source, _a1 error) *MockReportStore_CheckUpdates_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReportStore_CheckUpdates_Call) RunAndReturn(run func(model.Path, []model.Source) ([]model.Source, error)) *MockReportStore_CheckUpdates_Call {
	_c.Call.Return(run)
	return _c
}

// CleanReports provides a mock function with given fields: path, sources
func (_m *MockReportStore) CleanReports(path model.Path, sources []model.Source) error {
	ret := _m.Called(path, sources)

	if len(ret) == 0 {
		panic("no return value specified for CleanReports")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.Path, []model.Source) error); ok {
		r0 = rf(path, sources)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReportStore_CleanReports_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CleanReports'
type MockReportStore_CleanReports_Call struct {
	*mock.Call
}

// CleanReports is a helper method to define mock.On call
//   - path model.Path
//   - sources []model.Source
func (_e *MockReportStore_Expecter) CleanReports(path interface{}, sources interface{}) *MockReportStore_CleanReports_Call {
	return &MockReportStore_CleanReports_Call{Call: _e.mock.On("CleanReports", path, sources)}
}

func (_c *MockReportStore_CleanReports_Call) Run(run func(path model.Path, sources []model.Source)) *MockReportStore_CleanReports_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.Path), args[1].([]model.Source))
	})
	return _c
}

func (_c *MockReportStore_CleanReports_Call) Return(_a0 error) *MockReportStore_CleanReports_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReportStore_CleanReports_Call) RunAndReturn(run func(model.Path, []model.Source) error) *MockReportStore_CleanReports_Call {
	_c.Call.Return(run)
	return _c
}

// LoadReports provides a mock function with given fields: path
func (_m *MockReportStore) LoadReports(path model.Path) ([]model.Report, error) {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for LoadReports")
	}

	var r0 []model.Report
	var r1 error
	if rf, ok := ret.Get(0).(func(model.Path) ([]model.Report, error)); ok {
		return rf(path)
	}
	if rf, ok := ret.Get(0).(func(model.Path) []model.Report); ok {
		r0 = rf(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Report)
		}
	}

	if rf, ok := ret.Get(1).(func(model.Path) error); ok {
		r1 = rf(path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReportStore_LoadReports_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadReports'
type MockReportStore_LoadReports_Call struct {
	*mock.Call
}

// LoadReports is a helper method to define mock.On call
//   - path model.Path
func (_e *MockReportStore_Expecter) LoadReports(path interface{}) *MockReportStore_LoadReports_Call {
	return &MockReportStore_LoadReports_Call{Call: _e.mock.On("LoadReports", path)}
}

func (_c *MockReportStore_LoadReports_Call) Run(run func(path model.Path)) *MockReportStore_LoadReports_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.Path))
	})
	return _c
}

func (_c *MockReportStore_LoadReports_Call) Return(_a0 []model.Report, _a1 error) *MockReportStore_LoadReports_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReportStore_LoadReports_Call) RunAndReturn(run func(model.Path) ([]model.Report, error)) *MockReportStore_LoadReports_Call {
	_c.Call.Return(run)
	return _c
}

// RegenerateIndex provides a mock function with given fields: path
func (_m *MockReportStore) RegenerateIndex(path model.Path) error {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for RegenerateIndex")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.Path) error); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReportStore_RegenerateIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegenerateIndex'
type MockReportStore_RegenerateIndex_Call struct {
	*mock.Call
}

// RegenerateIndex is a helper method to define mock.On call
//   - path model.Path
func (_e *MockReportStore_Expecter) RegenerateIndex(path interface{}) *MockReportStore_RegenerateIndex_Call {
	return &MockReportStore_RegenerateIndex_Call{Call: _e.mock.On("RegenerateIndex", path)}
}

func (_c *MockReportStore_RegenerateIndex_Call) Run(run func(path model.Path)) *MockReportStore_RegenerateIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.Path))
	})
	return _c
}

func (_c *MockReportStore_RegenerateIndex_Call) Return(_a0 error) *MockReportStore_RegenerateIndex_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReportStore_RegenerateIndex_Call) RunAndReturn(run func(model.Path) error) *MockReportStore_RegenerateIndex_Call {
	_c.Call.Return(run)
	return _c
}

// SaveReports provides a mock function with given fields: path, reports
func (_m *MockReportStore) SaveReports(path model.Path, reports []model.Report) error {
	ret := _m.Called(path, reports)

	if len(ret) == 0 {
		panic("no return value specified for SaveReports")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.Path, []model.Report) error); ok {
		r0 = rf(path, reports)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReportStore_SaveReports_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveReports'
type MockReportStore_SaveReports_Call struct {
	*mock.Call
}

// SaveReports is a helper method to define mock.On call
//   - path model.Path
//   - reports []model.Report
func (_e *MockReportStore_Expecter) SaveReports(path interface{}, reports interface{}) *MockReportStore_SaveReports_Call {
	return &MockReportStore_SaveReports_Call{Call: _e.mock.On("SaveReports", path, reports)}
}

func (_c *MockReportStore_SaveReports_Call) Run(run func(path model.Path, reports []model.Report)) *MockReportStore_SaveReports_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.Path), args[1].([]model.Report))
	})
	return _c
}

func (_c *MockReportStore_SaveReports_Call) Return(_a0 error) *MockReportStore_SaveReports_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReportStore_SaveReports_Call) RunAndReturn(run func(model.Path, []model.Report) error) *MockReportStore_SaveReports_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReportStore creates a new instance of MockReportStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReportStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReportStore {
	mock := &MockReportStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
