// Code generated by mockery. DO NOT EDIT.

package domain

import (
	model "github.com/mouse-blink/gooze/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockOrchestrator is an autogenerated mock type for the Orchestrator type
type MockOrchestrator struct {
	mock.Mock
}

type MockOrchestrator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrchestrator) EXPECT() *MockOrchestrator_Expecter {
	return &MockOrchestrator_Expecter{mock: &_m.Mock}
}

// TestMutation provides a mock function with given fields: source, mutation
func (_m *MockOrchestrator) TestMutation(source model.Source, mutation model.Mutation) (model.Report, error) {
	ret := _m.Called(source, mutation)

	if len(ret) == 0 {
		panic("no return value specified for TestMutation")
	}

	var r0 model.Report
	var r1 error
	if rf, ok := ret.Get(0).(func(model.Source, model.Mutation) (model.Report, error)); ok {
		return rf(source, mutation)
	}
	if rf, ok := ret.Get(0).(func(model.Source, model.Mutation) model.Report); ok {
		r0 = rf(source, mutation)
	} else {
		r0 = ret.Get(0).(model.Report)
	}

	if rf, ok := ret.Get(1).(func(model.Source, model.Mutation) error); ok {
		r1 = rf(source, mutation)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrchestrator_TestMutation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TestMutation'
type MockOrchestrator_TestMutation_Call struct {
	*mock.Call
}

// TestMutation is a helper method to define mock.On call
//   - source model.Source
//   - mutation model.Mutation
func (_e *MockOrchestrator_Expecter) TestMutation(source interface{}, mutation interface{}) *MockOrchestrator_TestMutation_Call {
	return &MockOrchestrator_TestMutation_Call{Call: _e.mock.On("TestMutation", source, mutation)}
}

func (_c *MockOrchestrator_TestMutation_Call) Run(run func(source model.Source, mutation model.Mutation)) *MockOrchestrator_TestMutation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.Source), args[1].(model.Mutation))
	})
	return _c
}

func (_c *MockOrchestrator_TestMutation_Call) Return(_a0 model.Report, _a1 error) *MockOrchestrator_TestMutation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrchestrator_TestMutation_Call) RunAndReturn(run func(model.Source, model.Mutation) (model.Report, error)) *MockOrchestrator_TestMutation_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrchestrator creates a new instance of MockOrchestrator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrchestrator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrchestrator {
	mock := &MockOrchestrator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
