// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	model "github.com/mouse-blink/gooze/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockMutagen is an autogenerated mock type for the Mutagen type
type MockMutagen struct {
	mock.Mock
}

type MockMutagen_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMutagen) EXPECT() *MockMutagen_Expecter {
	return &MockMutagen_Expecter{mock: &_m.Mock}
}

// GenerateMutation provides a mock function with given fields: source, startingIndex, mutationTypes
func (_m *MockMutagen) GenerateMutation(source model.SourceV2, startingIndex int, mutationTypes ...model.MutationType) ([]model.MutationV2, error) {
	_va := make([]interface{}, len(mutationTypes))
	for _i := range mutationTypes {
		_va[_i] = mutationTypes[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, source, startingIndex)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GenerateMutation")
	}

	var r0 []model.MutationV2
	var r1 error
	if rf, ok := ret.Get(0).(func(model.SourceV2, int, ...model.MutationType) ([]model.MutationV2, error)); ok {
		return rf(source, startingIndex, mutationTypes...)
	}
	if rf, ok := ret.Get(0).(func(model.SourceV2, int, ...model.MutationType) []model.MutationV2); ok {
		r0 = rf(source, startingIndex, mutationTypes...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.MutationV2)
		}
	}

	if rf, ok := ret.Get(1).(func(model.SourceV2, int, ...model.MutationType) error); ok {
		r1 = rf(source, startingIndex, mutationTypes...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMutagen_GenerateMutation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateMutation'
type MockMutagen_GenerateMutation_Call struct {
	*mock.Call
}

// GenerateMutation is a helper method to define mock.On call
//   - source model.SourceV2
//   - startingIndex int
//   - mutationTypes ...model.MutationType
func (_e *MockMutagen_Expecter) GenerateMutation(source interface{}, startingIndex interface{}, mutationTypes ...interface{}) *MockMutagen_GenerateMutation_Call {
	return &MockMutagen_GenerateMutation_Call{Call: _e.mock.On("GenerateMutation",
		append([]interface{}{source, startingIndex}, mutationTypes...)...)}
}

func (_c *MockMutagen_GenerateMutation_Call) Run(run func(source model.SourceV2, startingIndex int, mutationTypes ...model.MutationType)) *MockMutagen_GenerateMutation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]model.MutationType, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(model.MutationType)
			}
		}
		run(args[0].(model.SourceV2), args[1].(int), variadicArgs...)
	})
	return _c
}

func (_c *MockMutagen_GenerateMutation_Call) Return(_a0 []model.MutationV2, _a1 error) *MockMutagen_GenerateMutation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMutagen_GenerateMutation_Call) RunAndReturn(run func(model.SourceV2, int, ...model.MutationType) ([]model.MutationV2, error)) *MockMutagen_GenerateMutation_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMutagen creates a new instance of MockMutagen. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMutagen(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMutagen {
	mock := &MockMutagen{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
