// Code generated by mockery. DO NOT EDIT.

package domain

import (
	model "github.com/mouse-blink/gooze/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockMutagen is an autogenerated mock type for the Mutagen type
type MockMutagen struct {
	mock.Mock
}

type MockMutagen_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMutagen) EXPECT() *MockMutagen_Expecter {
	return &MockMutagen_Expecter{mock: &_m.Mock}
}

// EstimateMutations provides a mock function with given fields: source, mutationTypes
func (_m *MockMutagen) EstimateMutations(source model.Source, mutationTypes ...model.MutationType) (int, error) {
	_va := make([]interface{}, len(mutationTypes))
	for _i := range mutationTypes {
		_va[_i] = mutationTypes[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, source)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for EstimateMutations")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(model.Source, ...model.MutationType) (int, error)); ok {
		return rf(source, mutationTypes...)
	}
	if rf, ok := ret.Get(0).(func(model.Source, ...model.MutationType) int); ok {
		r0 = rf(source, mutationTypes...)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(model.Source, ...model.MutationType) error); ok {
		r1 = rf(source, mutationTypes...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMutagen_EstimateMutations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EstimateMutations'
type MockMutagen_EstimateMutations_Call struct {
	*mock.Call
}

// EstimateMutations is a helper method to define mock.On call
//   - source model.Source
//   - mutationTypes ...model.MutationType
func (_e *MockMutagen_Expecter) EstimateMutations(source interface{}, mutationTypes ...interface{}) *MockMutagen_EstimateMutations_Call {
	return &MockMutagen_EstimateMutations_Call{Call: _e.mock.On("EstimateMutations",
		append([]interface{}{source}, mutationTypes...)...)}
}

func (_c *MockMutagen_EstimateMutations_Call) Run(run func(source model.Source, mutationTypes ...model.MutationType)) *MockMutagen_EstimateMutations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]model.MutationType, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(model.MutationType)
			}
		}
		run(args[0].(model.Source), variadicArgs...)
	})
	return _c
}

func (_c *MockMutagen_EstimateMutations_Call) Return(_a0 int, _a1 error) *MockMutagen_EstimateMutations_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMutagen_EstimateMutations_Call) RunAndReturn(run func(model.Source, ...model.MutationType) (int, error)) *MockMutagen_EstimateMutations_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateMutations provides a mock function with given fields: source, mutationTypes
func (_m *MockMutagen) GenerateMutations(source model.Source, mutationTypes ...model.MutationType) ([]model.Mutation, error) {
	_va := make([]interface{}, len(mutationTypes))
	for _i := range mutationTypes {
		_va[_i] = mutationTypes[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, source)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GenerateMutations")
	}

	var r0 []model.Mutation
	var r1 error
	if rf, ok := ret.Get(0).(func(model.Source, ...model.MutationType) ([]model.Mutation, error)); ok {
		return rf(source, mutationTypes...)
	}
	if rf, ok := ret.Get(0).(func(model.Source, ...model.MutationType) []model.Mutation); ok {
		r0 = rf(source, mutationTypes...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Mutation)
		}
	}

	if rf, ok := ret.Get(1).(func(model.Source, ...model.MutationType) error); ok {
		r1 = rf(source, mutationTypes...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMutagen_GenerateMutations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateMutations'
type MockMutagen_GenerateMutations_Call struct {
	*mock.Call
}

// GenerateMutations is a helper method to define mock.On call
//   - source model.Source
//   - mutationTypes ...model.MutationType
func (_e *MockMutagen_Expecter) GenerateMutations(source interface{}, mutationTypes ...interface{}) *MockMutagen_GenerateMutations_Call {
	return &MockMutagen_GenerateMutations_Call{Call: _e.mock.On("GenerateMutations",
		append([]interface{}{source}, mutationTypes...)...)}
}

func (_c *MockMutagen_GenerateMutations_Call) Run(run func(source model.Source, mutationTypes ...model.MutationType)) *MockMutagen_GenerateMutations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]model.MutationType, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(model.MutationType)
			}
		}
		run(args[0].(model.Source), variadicArgs...)
	})
	return _c
}

func (_c *MockMutagen_GenerateMutations_Call) Return(_a0 []model.Mutation, _a1 error) *MockMutagen_GenerateMutations_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMutagen_GenerateMutations_Call) RunAndReturn(run func(model.Source, ...model.MutationType) ([]model.Mutation, error)) *MockMutagen_GenerateMutations_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMutagen creates a new instance of MockMutagen. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMutagen(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMutagen {
	mock := &MockMutagen{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
