// Code generated by mockery. DO NOT EDIT.

package domain

import (
	model "github.com/mouse-blink/gooze/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockWorkflow is an autogenerated mock type for the Workflow type
type MockWorkflow struct {
	mock.Mock
}

type MockWorkflow_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWorkflow) EXPECT() *MockWorkflow_Expecter {
	return &MockWorkflow_Expecter{mock: &_m.Mock}
}

// EstimateMutations provides a mock function with given fields: sources, mutationType
func (_m *MockWorkflow) EstimateMutations(sources model.Source, mutationType ...model.MutationType) (int, error) {
	_va := make([]interface{}, len(mutationType))
	for _i := range mutationType {
		_va[_i] = mutationType[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, sources)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for EstimateMutations")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(model.Source, ...model.MutationType) (int, error)); ok {
		return rf(sources, mutationType...)
	}
	if rf, ok := ret.Get(0).(func(model.Source, ...model.MutationType) int); ok {
		r0 = rf(sources, mutationType...)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(model.Source, ...model.MutationType) error); ok {
		r1 = rf(sources, mutationType...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWorkflow_EstimateMutations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EstimateMutations'
type MockWorkflow_EstimateMutations_Call struct {
	*mock.Call
}

// EstimateMutations is a helper method to define mock.On call
//   - sources model.Source
//   - mutationType ...model.MutationType
func (_e *MockWorkflow_Expecter) EstimateMutations(sources interface{}, mutationType ...interface{}) *MockWorkflow_EstimateMutations_Call {
	return &MockWorkflow_EstimateMutations_Call{Call: _e.mock.On("EstimateMutations",
		append([]interface{}{sources}, mutationType...)...)}
}

func (_c *MockWorkflow_EstimateMutations_Call) Run(run func(sources model.Source, mutationType ...model.MutationType)) *MockWorkflow_EstimateMutations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]model.MutationType, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(model.MutationType)
			}
		}
		run(args[0].(model.Source), variadicArgs...)
	})
	return _c
}

func (_c *MockWorkflow_EstimateMutations_Call) Return(_a0 int, _a1 error) *MockWorkflow_EstimateMutations_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWorkflow_EstimateMutations_Call) RunAndReturn(run func(model.Source, ...model.MutationType) (int, error)) *MockWorkflow_EstimateMutations_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateMutations provides a mock function with given fields: sources, mutationType
func (_m *MockWorkflow) GenerateMutations(sources model.Source, mutationType ...model.MutationType) ([]model.Mutation, error) {
	_va := make([]interface{}, len(mutationType))
	for _i := range mutationType {
		_va[_i] = mutationType[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, sources)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GenerateMutations")
	}

	var r0 []model.Mutation
	var r1 error
	if rf, ok := ret.Get(0).(func(model.Source, ...model.MutationType) ([]model.Mutation, error)); ok {
		return rf(sources, mutationType...)
	}
	if rf, ok := ret.Get(0).(func(model.Source, ...model.MutationType) []model.Mutation); ok {
		r0 = rf(sources, mutationType...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Mutation)
		}
	}

	if rf, ok := ret.Get(1).(func(model.Source, ...model.MutationType) error); ok {
		r1 = rf(sources, mutationType...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWorkflow_GenerateMutations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateMutations'
type MockWorkflow_GenerateMutations_Call struct {
	*mock.Call
}

// GenerateMutations is a helper method to define mock.On call
//   - sources model.Source
//   - mutationType ...model.MutationType
func (_e *MockWorkflow_Expecter) GenerateMutations(sources interface{}, mutationType ...interface{}) *MockWorkflow_GenerateMutations_Call {
	return &MockWorkflow_GenerateMutations_Call{Call: _e.mock.On("GenerateMutations",
		append([]interface{}{sources}, mutationType...)...)}
}

func (_c *MockWorkflow_GenerateMutations_Call) Run(run func(sources model.Source, mutationType ...model.MutationType)) *MockWorkflow_GenerateMutations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]model.MutationType, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(model.MutationType)
			}
		}
		run(args[0].(model.Source), variadicArgs...)
	})
	return _c
}

func (_c *MockWorkflow_GenerateMutations_Call) Return(_a0 []model.Mutation, _a1 error) *MockWorkflow_GenerateMutations_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWorkflow_GenerateMutations_Call) RunAndReturn(run func(model.Source, ...model.MutationType) ([]model.Mutation, error)) *MockWorkflow_GenerateMutations_Call {
	_c.Call.Return(run)
	return _c
}

// GetSources provides a mock function with given fields: roots
func (_m *MockWorkflow) GetSources(roots ...model.Path) ([]model.Source, error) {
	_va := make([]interface{}, len(roots))
	for _i := range roots {
		_va[_i] = roots[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetSources")
	}

	var r0 []model.Source
	var r1 error
	if rf, ok := ret.Get(0).(func(...model.Path) ([]model.Source, error)); ok {
		return rf(roots...)
	}
	if rf, ok := ret.Get(0).(func(...model.Path) []model.Source); ok {
		r0 = rf(roots...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Source)
		}
	}

	if rf, ok := ret.Get(1).(func(...model.Path) error); ok {
		r1 = rf(roots...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWorkflow_GetSources_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSources'
type MockWorkflow_GetSources_Call struct {
	*mock.Call
}

// GetSources is a helper method to define mock.On call
//   - roots ...model.Path
func (_e *MockWorkflow_Expecter) GetSources(roots ...interface{}) *MockWorkflow_GetSources_Call {
	return &MockWorkflow_GetSources_Call{Call: _e.mock.On("GetSources",
		append([]interface{}{}, roots...)...)}
}

func (_c *MockWorkflow_GetSources_Call) Run(run func(roots ...model.Path)) *MockWorkflow_GetSources_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]model.Path, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(model.Path)
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockWorkflow_GetSources_Call) Return(_a0 []model.Source, _a1 error) *MockWorkflow_GetSources_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWorkflow_GetSources_Call) RunAndReturn(run func(...model.Path) ([]model.Source, error)) *MockWorkflow_GetSources_Call {
	_c.Call.Return(run)
	return _c
}

// RunMutationTests provides a mock function with given fields: sources, threads
func (_m *MockWorkflow) RunMutationTests(sources []model.Source, threads int) (map[model.Path]model.FileResult, error) {
	ret := _m.Called(sources, threads)

	if len(ret) == 0 {
		panic("no return value specified for RunMutationTests")
	}

	var r0 map[model.Path]model.FileResult
	var r1 error
	if rf, ok := ret.Get(0).(func([]model.Source, int) (map[model.Path]model.FileResult, error)); ok {
		return rf(sources, threads)
	}
	if rf, ok := ret.Get(0).(func([]model.Source, int) map[model.Path]model.FileResult); ok {
		r0 = rf(sources, threads)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[model.Path]model.FileResult)
		}
	}

	if rf, ok := ret.Get(1).(func([]model.Source, int) error); ok {
		r1 = rf(sources, threads)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWorkflow_RunMutationTests_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunMutationTests'
type MockWorkflow_RunMutationTests_Call struct {
	*mock.Call
}

// RunMutationTests is a helper method to define mock.On call
//   - sources []model.Source
//   - threads int
func (_e *MockWorkflow_Expecter) RunMutationTests(sources interface{}, threads interface{}) *MockWorkflow_RunMutationTests_Call {
	return &MockWorkflow_RunMutationTests_Call{Call: _e.mock.On("RunMutationTests", sources, threads)}
}

func (_c *MockWorkflow_RunMutationTests_Call) Run(run func(sources []model.Source, threads int)) *MockWorkflow_RunMutationTests_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]model.Source), args[1].(int))
	})
	return _c
}

func (_c *MockWorkflow_RunMutationTests_Call) Return(_a0 map[model.Path]model.FileResult, _a1 error) *MockWorkflow_RunMutationTests_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWorkflow_RunMutationTests_Call) RunAndReturn(run func([]model.Source, int) (map[model.Path]model.FileResult, error)) *MockWorkflow_RunMutationTests_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWorkflow creates a new instance of MockWorkflow. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWorkflow(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWorkflow {
	mock := &MockWorkflow{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
