---
version: '2'
run:
  timeout: 5m
  tests: false
  allow-parallel-runners: true

linters:
  disable:
  - depguard
  - exhaustruct
  - gochecknoinits
  - wsl
  enable:
  - revive
  - staticcheck
  - govet
  - errcheck
  - wsl_v5
  - funlen

linters-settings:
  funlen:
    lines: 50
    statements: 30
    ignore-comments: true
  wsl_v5:
    allow-first-in-block: true
    allow-whole-block: false
    branch-max-lines: 2

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-files:
  - .*_test\.go$
  exclude-dirs:
  - examples
