// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	controller "github.com/mouse-blink/gooze/internal/controller"
	mock "github.com/stretchr/testify/mock"

	model "github.com/mouse-blink/gooze/internal/model"
)

// MockUI is an autogenerated mock type for the UI type
type MockUI struct {
	mock.Mock
}

type MockUI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUI) EXPECT() *MockUI_Expecter {
	return &MockUI_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockUI) Close() {
	_m.Called()
}

// MockUI_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockUI_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockUI_Expecter) Close() *MockUI_Close_Call {
	return &MockUI_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockUI_Close_Call) Run(run func()) *MockUI_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUI_Close_Call) Return() *MockUI_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockUI_Close_Call) RunAndReturn(run func()) *MockUI_Close_Call {
	_c.Run(run)
	return _c
}

// DisplayCompletedTestInfo provides a mock function with given fields: currentMutation, mutationResult
func (_m *MockUI) DisplayCompletedTestInfo(currentMutation model.Mutation, mutationResult model.Result) {
	_m.Called(currentMutation, mutationResult)
}

// MockUI_DisplayCompletedTestInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisplayCompletedTestInfo'
type MockUI_DisplayCompletedTestInfo_Call struct {
	*mock.Call
}

// DisplayCompletedTestInfo is a helper method to define mock.On call
//   - currentMutation model.Mutation
//   - mutationResult model.Result
func (_e *MockUI_Expecter) DisplayCompletedTestInfo(currentMutation interface{}, mutationResult interface{}) *MockUI_DisplayCompletedTestInfo_Call {
	return &MockUI_DisplayCompletedTestInfo_Call{Call: _e.mock.On("DisplayCompletedTestInfo", currentMutation, mutationResult)}
}

func (_c *MockUI_DisplayCompletedTestInfo_Call) Run(run func(currentMutation model.Mutation, mutationResult model.Result)) *MockUI_DisplayCompletedTestInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.Mutation), args[1].(model.Result))
	})
	return _c
}

func (_c *MockUI_DisplayCompletedTestInfo_Call) Return() *MockUI_DisplayCompletedTestInfo_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockUI_DisplayCompletedTestInfo_Call) RunAndReturn(run func(model.Mutation, model.Result)) *MockUI_DisplayCompletedTestInfo_Call {
	_c.Run(run)
	return _c
}

// DisplayConcurencyInfo provides a mock function with given fields: threads, shardIndex, shardCount
func (_m *MockUI) DisplayConcurencyInfo(threads int, shardIndex int, shardCount int) {
	_m.Called(threads, shardIndex, shardCount)
}

// MockUI_DisplayConcurencyInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisplayConcurencyInfo'
type MockUI_DisplayConcurencyInfo_Call struct {
	*mock.Call
}

// DisplayConcurencyInfo is a helper method to define mock.On call
//   - threads int
//   - shardIndex int
//   - shardCount int
func (_e *MockUI_Expecter) DisplayConcurencyInfo(threads interface{}, shardIndex interface{}, shardCount interface{}) *MockUI_DisplayConcurencyInfo_Call {
	return &MockUI_DisplayConcurencyInfo_Call{Call: _e.mock.On("DisplayConcurencyInfo", threads, shardIndex, shardCount)}
}

func (_c *MockUI_DisplayConcurencyInfo_Call) Run(run func(threads int, shardIndex int, shardCount int)) *MockUI_DisplayConcurencyInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockUI_DisplayConcurencyInfo_Call) Return() *MockUI_DisplayConcurencyInfo_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockUI_DisplayConcurencyInfo_Call) RunAndReturn(run func(int, int, int)) *MockUI_DisplayConcurencyInfo_Call {
	_c.Run(run)
	return _c
}

// DisplayEstimation provides a mock function with given fields: mutations, err
func (_m *MockUI) DisplayEstimation(mutations []model.Mutation, err error) error {
	ret := _m.Called(mutations, err)

	if len(ret) == 0 {
		panic("no return value specified for DisplayEstimation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]model.Mutation, error) error); ok {
		r0 = rf(mutations, err)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUI_DisplayEstimation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisplayEstimation'
type MockUI_DisplayEstimation_Call struct {
	*mock.Call
}

// DisplayEstimation is a helper method to define mock.On call
//   - mutations []model.Mutation
//   - err error
func (_e *MockUI_Expecter) DisplayEstimation(mutations interface{}, err interface{}) *MockUI_DisplayEstimation_Call {
	return &MockUI_DisplayEstimation_Call{Call: _e.mock.On("DisplayEstimation", mutations, err)}
}

func (_c *MockUI_DisplayEstimation_Call) Run(run func(mutations []model.Mutation, err error)) *MockUI_DisplayEstimation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]model.Mutation), args[1].(error))
	})
	return _c
}

func (_c *MockUI_DisplayEstimation_Call) Return(_a0 error) *MockUI_DisplayEstimation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUI_DisplayEstimation_Call) RunAndReturn(run func([]model.Mutation, error) error) *MockUI_DisplayEstimation_Call {
	_c.Call.Return(run)
	return _c
}

// DisplayStartingTestInfo provides a mock function with given fields: currentMutation, threadID
func (_m *MockUI) DisplayStartingTestInfo(currentMutation model.Mutation, threadID int) {
	_m.Called(currentMutation, threadID)
}

// MockUI_DisplayStartingTestInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisplayStartingTestInfo'
type MockUI_DisplayStartingTestInfo_Call struct {
	*mock.Call
}

// DisplayStartingTestInfo is a helper method to define mock.On call
//   - currentMutation model.Mutation
//   - threadID int
func (_e *MockUI_Expecter) DisplayStartingTestInfo(currentMutation interface{}, threadID interface{}) *MockUI_DisplayStartingTestInfo_Call {
	return &MockUI_DisplayStartingTestInfo_Call{Call: _e.mock.On("DisplayStartingTestInfo", currentMutation, threadID)}
}

func (_c *MockUI_DisplayStartingTestInfo_Call) Run(run func(currentMutation model.Mutation, threadID int)) *MockUI_DisplayStartingTestInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.Mutation), args[1].(int))
	})
	return _c
}

func (_c *MockUI_DisplayStartingTestInfo_Call) Return() *MockUI_DisplayStartingTestInfo_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockUI_DisplayStartingTestInfo_Call) RunAndReturn(run func(model.Mutation, int)) *MockUI_DisplayStartingTestInfo_Call {
	_c.Run(run)
	return _c
}

// DusplayUpcomingTestsInfo provides a mock function with given fields: i
func (_m *MockUI) DusplayUpcomingTestsInfo(i int) {
	_m.Called(i)
}

// MockUI_DusplayUpcomingTestsInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DusplayUpcomingTestsInfo'
type MockUI_DusplayUpcomingTestsInfo_Call struct {
	*mock.Call
}

// DusplayUpcomingTestsInfo is a helper method to define mock.On call
//   - i int
func (_e *MockUI_Expecter) DusplayUpcomingTestsInfo(i interface{}) *MockUI_DusplayUpcomingTestsInfo_Call {
	return &MockUI_DusplayUpcomingTestsInfo_Call{Call: _e.mock.On("DusplayUpcomingTestsInfo", i)}
}

func (_c *MockUI_DusplayUpcomingTestsInfo_Call) Run(run func(i int)) *MockUI_DusplayUpcomingTestsInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockUI_DusplayUpcomingTestsInfo_Call) Return() *MockUI_DusplayUpcomingTestsInfo_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockUI_DusplayUpcomingTestsInfo_Call) RunAndReturn(run func(int)) *MockUI_DusplayUpcomingTestsInfo_Call {
	_c.Run(run)
	return _c
}

// Start provides a mock function with given fields: options
func (_m *MockUI) Start(options ...controller.StartOption) error {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(...controller.StartOption) error); ok {
		r0 = rf(options...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUI_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockUI_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - options ...controller.StartOption
func (_e *MockUI_Expecter) Start(options ...interface{}) *MockUI_Start_Call {
	return &MockUI_Start_Call{Call: _e.mock.On("Start",
		append([]interface{}{}, options...)...)}
}

func (_c *MockUI_Start_Call) Run(run func(options ...controller.StartOption)) *MockUI_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]controller.StartOption, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(controller.StartOption)
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockUI_Start_Call) Return(_a0 error) *MockUI_Start_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUI_Start_Call) RunAndReturn(run func(...controller.StartOption) error) *MockUI_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Wait provides a mock function with no fields
func (_m *MockUI) Wait() {
	_m.Called()
}

// MockUI_Wait_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Wait'
type MockUI_Wait_Call struct {
	*mock.Call
}

// Wait is a helper method to define mock.On call
func (_e *MockUI_Expecter) Wait() *MockUI_Wait_Call {
	return &MockUI_Wait_Call{Call: _e.mock.On("Wait")}
}

func (_c *MockUI_Wait_Call) Run(run func()) *MockUI_Wait_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUI_Wait_Call) Return() *MockUI_Wait_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockUI_Wait_Call) RunAndReturn(run func()) *MockUI_Wait_Call {
	_c.Run(run)
	return _c
}

// NewMockUI creates a new instance of MockUI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUI {
	mock := &MockUI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
