// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	controller "github.com/mouse-blink/gooze/internal/controller"
	mock "github.com/stretchr/testify/mock"
)

// MockStartOption is an autogenerated mock type for the StartOption type
type MockStartOption struct {
	mock.Mock
}

type MockStartOption_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStartOption) EXPECT() *MockStartOption_Expecter {
	return &MockStartOption_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0
func (_m *MockStartOption) Execute(_a0 *controller.StartConfig) {
	_m.Called(_a0)
}

// MockStartOption_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockStartOption_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 *controller.StartConfig
func (_e *MockStartOption_Expecter) Execute(_a0 interface{}) *MockStartOption_Execute_Call {
	return &MockStartOption_Execute_Call{Call: _e.mock.On("Execute", _a0)}
}

func (_c *MockStartOption_Execute_Call) Run(run func(_a0 *controller.StartConfig)) *MockStartOption_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*controller.StartConfig))
	})
	return _c
}

func (_c *MockStartOption_Execute_Call) Return() *MockStartOption_Execute_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockStartOption_Execute_Call) RunAndReturn(run func(*controller.StartConfig)) *MockStartOption_Execute_Call {
	_c.Run(run)
	return _c
}

// NewMockStartOption creates a new instance of MockStartOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStartOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStartOption {
	mock := &MockStartOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
